name: Check GHA Download

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  download:
    runs-on: ubuntu-latest
#     env:
#       JUST_VERSION: 1.8.0 # https://github.com/casey/just/releases
#       TERA_VERSION: 0.2.2 # https://github.com/chevdor/tera-cli/release
#       YQ_VERSION: 4.30.4 # https://github.com/mikefarah/yq/releases
    steps:
      - name: foo
        run: echo FOO
#       - name: Install Tools
#         run: |
#           wget -O ${{ runner.temp }}/just.tar.gz https://github.com/casey/just/releases/download/${JUST_VERSION}/just-${JUST_VERSION}-x86_64-unknown-linux-musl.tar.gz && \
#           tar xf ${{ runner.temp }}/just.tar.gz && mv just /usr/local/bin && \
#           wget -O ${{ runner.temp }}/tera.deb https://github.com/chevdor/tera-cli/releases/download/v${TERA_VERSION}/tera-cli_linux_amd64.deb && \
#           sudo dpkg -i ${{ runner.temp }}/tera.deb && \
#           wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v${YQ_VERSION}/yq_linux_amd64
#       - name: Checkout
#         uses: actions/checkout@v3
#         with:
#           submodules: recursive
#       - name: Render Doc
#         run: |
#           just md
