name: Check Doc

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    env:
      JUST_VERSION: 1.8.0 # https://github.com/casey/just/releases
      TERA_VERSION: 0.2.2 # https://github.com/chevdor/tera-cli/release
      YQ_VERSION: 4.30.4 # https://github.com/mikefarah/yq/releases
    steps:
      - name: Install Tools
        run: |
          wget -O ${{ runner.temp }}/just.tar.gz https://github.com/casey/just/releases/download/${JUST_VERSION}/just-${JUST_VERSION}-x86_64-unknown-linux-musl.tar.gz && \
          tar xf ${{ runner.temp }}/just.tar.gz && mv just /usr/local/bin && \
          wget -O ${{ runner.temp }}/tera.deb https://github.com/chevdor/tera-cli/releases/download/v${TERA_VERSION}/tera-cli_linux_amd64.deb && \
          sudo dpkg -i ${{ runner.temp }}/tera.deb && \
          wget -O ${{ runner.temp }}/pandoc.deb https://github.com/jgm/pandoc/releases/download/2.19.2/pandoc-2.19.2-1-amd64.deb && \
          sudo dpkg -i ${{ runner.temp }}/pandoc.deb && \
          wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v${YQ_VERSION}/yq_linux_amd64
          sudo apt-get install -y asciidoctor

          just --version
          tera --version
          pandoc --version
          asciidoctor --version

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Render Doc
        run: |
          just md
